### PR TITLE
fix(markdown): do not render comments

### LINKED ISSUE #1035: Excerpt does not work
### Version
@nuxt/content: v2
nuxt: v3

### Steps to reproduce

Add `<!--more-->` into a markdown file in `playground/` and run `yarn dev`

### What is Expected?

To work and add a `excerpt` key in the document.

### Note

How would we use the excerpt in Markdown, shall we have an option for the `<Content/>` component?

### PR DESCRIPTION
**Pull request by farnabaz**
### 🔗 Linked issue

resolves #1035 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Atinux** [comment]
Ready to review @farnabaz ?

File: test/features/parser-markdown.ts [hunk 1]
```diff
@@ -37,5 +37,23 @@ export const testMarkdownParser = () => {
       expect(parsed.body).toHaveProperty('children[0].tag', 'p')
       expect(parsed.body).toHaveProperty('children[0].children[0].tag', 'code-inline')
     })
+
+    test('comment', async () => {
+      const parsed = await $fetch('/api/parse', {
+        method: 'POST',
+        body: {
+          id: 'content:index.md',
+          content: '<!-- coment -->'
```
Comment (Atinux) [inline test/features/parser-markdown.ts:46]:
```suggestion
          content: '<!-- comment -->'
```

**Comment by Atinux** [comment]
Would be nice to add a test for `excerpt` @farnabaz
