### PR TITLE
fix: avoid registering `components/global` when not exists

### LINKED ISSUE #547: [theme-docs] avoid registering `components/global` when does not exists
### Version
@nuxt/content: 1.5.0
nuxt: 2.x

### Steps to reproduce

- yarn create nuxt-content-docs

### What is Expected?

Not to register `components/global` when does not exist and avoid warning 

### What is actually happening?

> WARN Components directory not found: ~/components/global

### PR DESCRIPTION
**Pull request by pi0**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
Fixes #547 

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

File: packages/theme-docs/src/index.js [hunk 1]
```diff
@@ -47,13 +47,6 @@ const defaultConfig = {
       nuxt.options.content.dir = path.resolve(nuxt.options.rootDir, nuxt.options.content.dir || 'content')
       // Configure `static/ dir
       nuxt.options.dir.static = path.resolve(nuxt.options.rootDir, nuxt.options.dir.static || 'static')
-      // Configure `components/` dir
```
Comment (benjamincanac) [inline packages/theme-docs/src/index.js:50]: @pi0 Why removing this?

The theme needs to load global components inside the theme itself and the ones from the `rootDir`.

Comment (pi0) [reply packages/theme-docs/src/index.js:50]: You are right. Using `rootDir` was little bit misleading. I've updated it to `__dirname`

Comment (benjamincanac) [reply packages/theme-docs/src/index.js:50]: @pi0 This has to be `nuxt.options.rootDir`, @nuxt/content is already loading the theme components, here `__dirname` also resolves to the theme so user components are not loaded anymore.

Comment (pi0) [reply packages/theme-docs/src/index.js:50]: Hmm i not sure to unrestand. `rootDir` cannot point to two directories. `rootDir` should be same as `__dirname` (path to `node_modules/@nuxt/theme/docs/src`. User components are loaded by the other hook in main content module

Comment (benjamincanac) [reply packages/theme-docs/src/index.js:50]: Since the `srcDir` is the theme, the main content module is loading the theme components, `rootDir` however loads the user components.

Comment (benjamincanac) [reply packages/theme-docs/src/index.js:50]: You can try to create a component in the `docs/` for example, they won't be loaded with the `__dirname` change.

**Comment by Atinux** [comment]
I will look at it too, it was in my todo list :)

I think we need to keep rootDir (user directory when using the docs theme).

Also I would like to watch the creation of the global/ directory in order to restart Nuxt.

On top of it, since we have the PR for overwriting components, we will have to wait for it to be merged since it will be two directories to watch

File: packages/theme-docs/src/index.js (hunk 1 above)
Comment (pi0) [reply packages/theme-docs/src/index.js]: ok you are right reverted :)

**Comment by pi0** [comment]
> On top of it, since we have the PR for overwriting components, we will have to wait for it to be merged since it will be two directories to watch

I'm not sure it will we merged in near future because is a breaking change and also not related to this fix

**Comment by Atinux** [comment]
You are right.

Can we watch the repository creation (if does not exists) to restart Nuxt: `nuxt.options.watch(join(nuxt.options.srcDir, 'components/global/'))`

What is the current behavior if you start Nuxt, then add a component to components/global/?

**Review by benjamincanac — APPROVED** [review]

**Review by benjamincanac — APPROVED** [review]
