### PR TITLE
fix: allow ] in filename code block

### LINKED ISSUE #2166: in documents, filename "[...slug].vue" above code block display not correctly
### Environment

- Operating System: Darwin
- Node Version:     v16.18.0
- Nuxt Version:     0.0.0
- Nitro Version:    -
- Package Manager:  PNPM
- Builder:          webpack
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://content.nuxtjs.org/api/components/content-doc#contentdoc

### Describe the bug

image

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by Barbapapazes**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

fix #2166 

For a code block, if filename was `[...page].vue`, regex was stoping at `[...page`. This PR fix it.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: src/runtime/markdown-parser/handler/utils.ts [hunk 1]
```diff
@@ -20,7 +20,7 @@ export function parseThematicBlock (lang: string) {
 
   const language = lang.replace(/[{|[](.+)/, '').match(/^[^ \t]+(?=[ \t]|$)/)
   const highlightTokens = lang.match(/{([^}]*)}/)
-  const filenameTokens = lang.match(/\[([^\]]*)\]/)
+  const filenameTokens = lang.match(/\[(.*)\]/) /** Allow ']' in filename. @see https://regex101.com/r/Hm0t5m/1 */
```
Comment (nobkd) [inline src/runtime/markdown-parser/handler/utils.ts:23]: I think we used `[^\]]` to allow using lists in the meta part.
Here's an example what would not work anymore if we match the longest string.
> \```language [filename]{hightlights} meta=[...]

It would match the content `filename]{hightlights} meta=[...`

Comment (nobkd) [reply src/runtime/markdown-parser/handler/utils.ts:23]: I thought we could use something like `\[` in the markdown and prevent matching those somehow

Comment (Barbapapazes) [reply src/runtime/markdown-parser/handler/utils.ts:23]: Oooh I understand. I do it too quickly!

Comment (nobkd) [reply src/runtime/markdown-parser/handler/utils.ts:23]: I think, that this might work: `/\[((\\]|[^\]])*)\]/`

---

This part `(\\]|[^\]])*` matches one or a sequence of: `\]` or characters that are not `]`

Only if our string has no more `]` after a `\]` it terminates the match at a `\]`.

e.g.

```
```ts [[...slug\].vue] meta=[]
```

=> `[...slug\].vue` as the first group match. Then we only have to replace `\]` which in reality is `\\]` with `]`-es

Comment (nobkd) [inline src/runtime/markdown-parser/handler/utils.ts:23]:
```suggestion
  const filenameTokens = lang.match(/\[((\\]|[^\]])*)\]/)
```

Comment (nobkd) [reply src/runtime/markdown-parser/handler/utils.ts:23]: And because of GitHub, I'm not allowed to suggest changes out of some range:

Change for L29:

```diff
-    filename: Array.isArray(filenameTokens) && filenameTokens[1] ? filenameTokens[1] : undefined,
+    filename: Array.isArray(filenameTokens) && filenameTokens[1] ? filenameTokens[1].replace(/\\]/g, ']') : undefined,
```

File: src/runtime/markdown-parser/handler/utils.ts [hunk 2]
```diff
@@ -20,7 +20,7 @@ export function parseThematicBlock (lang: string) {
...
   const meta = lang.replace(/^\w*\s*(\[[^\]]*\]|\{[^}]*\})?\s*(\[[^\]]*\]|\{[^}]*\})?\s*/, '')
```
Comment (nobkd) [inline src/runtime/markdown-parser/handler/utils.ts:24]:
```suggestion
  const meta = lang.replace(/^\w*\s*(\[((\\]|[^\]])*)\]|\{[^}]*\})?\s*(\[((\\]|[^\]])*)\]|\{[^}]*\})?\s*/, '')
```

To replace the correct part to have the meta left

**Review by nobkd — CHANGES_REQUESTED** [review]
This should be all the necessary changes, but we'll see..
This is currently not really tested.

I tried both `\\]` and `\]` and it seems that we need the first variant with two backslashes to get one real backslash from the Markdown.

So this should work:
```md
```ts [[...slug\\].vue] ...
```

File: src/runtime/markdown-parser/handler/utils.ts (hunk 1 above)
Comment (nobkd) [reply src/runtime/markdown-parser/handler/utils.ts:23]: Question is... is `\` or `\\` in Markdown a backslash?
Do we have to write `\\]` or `\]` in the markdown file?

Comment (Barbapapazes) [reply src/runtime/markdown-parser/handler/utils.ts:23]: Yes but if there is no meta, this regex is not working

https://regex101.com/r/bG0Net/1

Comment (Barbapapazes) [reply src/runtime/markdown-parser/handler/utils.ts:23]: For test, I think that we need to extract these utilities into simple function to be able to unit tests them.

**Comment by Barbapapazes** [comment]
I will also update documentation to add to warning about usage.

File: src/runtime/markdown-parser/handler/utils.ts (hunk 2 above)
Comment (Barbapapazes) [reply src/runtime/markdown-parser/handler/utils.ts]: I refactor this to be more understandable.

File: src/runtime/markdown-parser/handler/utils.ts [hunk 3]
```diff
@@ -18,15 +18,19 @@ export function parseThematicBlock (lang: string) {
     }
   }
 
-  const language = lang.replace(/[{|[](.+)/, '').match(/^[^ \t]+(?=[ \t]|$)/)
-  const highlightTokens = lang.match(/{([^}]*)}/)
-  const filenameTokens = lang.match(/\[([^\]]*)\]/)
-  const meta = lang.replace(/^\w*\s*(\[[^\]]*\]|\{[^}]*\})?\s*(\[[^\]]*\]|\{[^}]*\})?\s*/, '')
+  const languageMatches = lang.replace(/[{|[](.+)/, '').match(/^[^ \t]+(?=[ \t]|$)/)
+  const highlightTokensMatches = lang.match(/{([^}]*)}/)
+  const filenameMatches = lang.match(/\[((\S)*)\]/) /** Allow ']' in filename. */
```
Comment (nobkd) [inline src/runtime/markdown-parser/handler/utils.ts:23]: I can see that you don't want an escape character to have `]` in your filename, but we didn't want to depend on spaces. If we now change this, it could be a breaking change.

My variant from before would introduce an escape character (e.g. `\\`) for `]` but
- would not need spaces after the last `]` that belongs to the filename
- allow spaces in the filename.


You could not do this anymore:

```md
```ts [filename]meta=[]
```

or

```md
```ts [filename/title with spaces]
```

Spaces in the filename for example are already used in the `nuxt/nuxt` docs. Some examples:
- https://github.com/nuxt/nuxt/blob/350788419c414317354de9900cd049fa750456cc/docs/7.migration/4.meta.md?plain=1#L27
- https://github.com/nuxt/nuxt/blob/350788419c414317354de9900cd049fa750456cc/docs/1.getting-started/5.routing.md?plain=1#L17
- https://github.com/nuxt/nuxt/blob/350788419c414317354de9900cd049fa750456cc/docs/1.getting-started/5.routing.md?plain=1#L25

---

#2067 was the last change to this regexes, there should also be some ideas.

**Review by nobkd — CHANGES_REQUESTED** [review]

File: src/runtime/markdown-parser/handler/utils.ts (hunk 3 above)
Comment (Barbapapazes) [reply src/runtime/markdown-parser/handler/utils.ts:23]: you've convinced me. I will update regex to allow esacape ] and update docs in that ways (documenting why we choose this method).

Comment (nobkd) [inline src/runtime/markdown-parser/handler/utils.ts:23]:
```suggestion
  const filenameMatches = lang.match(\[((\\]|[^\]])*)\]/)
```

File: src/runtime/markdown-parser/handler/utils.ts [hunk 4]
```diff
@@ -18,15 +18,19 @@ export function parseThematicBlock (lang: string) {
...
+    .replace(highlightTokensMatches?.[0] ?? '', '')
+    .replace(filenameMatches?.[0] ?? '', '')
+    .trim()
 
   return {
-    language: language ? language[0] : undefined,
-    highlights: parseHighlightedLines(highlightTokens && highlightTokens[1]),
-    filename: Array.isArray(filenameTokens) && filenameTokens[1] ? filenameTokens[1] : undefined,
+    language: languageMatches?.[0] || undefined,
+    highlights: parseHighlightedLines(highlightTokensMatches?.[1] || undefined),
```
Comment (nobkd) [inline src/runtime/markdown-parser/handler/utils.ts:32]:
```suggestion
    highlights: parseHighlightedLines(highlightTokensMatches?.[1].replace(/\\]/g, ']') || undefined),
```

**Review by nobkd — CHANGES_REQUESTED** [review]

File: src/runtime/markdown-parser/handler/utils.ts [hunk 5]
```diff
@@ -18,15 +18,19 @@ export function parseThematicBlock (lang: string) {
...
-  const filenameTokens = lang.match(/\[([^\]]*)\]/)
-  const meta = lang.replace(/^\w*\s*(\[[^\]]*\]|\{[^}]*\})?\s*(\[[^\]]*\]|\{[^}]*\})?\s*/, '')
+  const languageMatches = lang.replace(/[{|[](.+)/, '').match(/^[^ \t]+(?=[ \t]|$)/)
+  const highlightTokensMatches = lang.match(/{([^}]*)}/)
+  const filenameMatches = lang.match(/\[((\S)*)\]/) /** Allow ']' in filename. */
+  const meta = lang
+    .replace(languageMatches?.[0] ?? '', '')
+    .replace(highlightTokensMatches?.[0] ?? '', '')
+    .replace(filenameMatches?.[0] ?? '', '')
+    .trim()
```
Comment (nobkd) [inline src/runtime/markdown-parser/handler/utils.ts:28]: Thanks for this, it makes this part so much more readable! ❤️

**Comment by Barbapapazes** [comment]
@nobkd we have an issue because a JS string is automatically escape `\` in string. So `[[...page\].vue]` is resolved as `[[...page].vue]` 

image

**Comment by Barbapapazes** [comment]
We will need to use a double `\`. I'll update PR with this usage.

**Comment by nobkd** [comment]
See this https://github.com/nuxt/content/pull/2169#pullrequestreview-1527240638

We need to use double escaping: `\\]`

There's probably a better escape character, but `\` is the generally used one, so I went with it. Do you have a better idea how to escape?

**Comment by nobkd** [comment]
> We will need to use a double `\`. I'll update PR with this usage.

Exactly

**Comment by Barbapapazes** [comment]
> See this [#2169 (review)](https://github.com/nuxt/content/pull/2169#pullrequestreview-1527240638)
> 
> We need to use double escaping: `\\]`
> 
> There's probably a better escape character, but `\` is the generally used one, so I went with it. Do you have a better idea how to escape?

Oh yes, I've not seen this comment! Thanks

File: docs/content/4.api/1.components/2.content-renderer.md [hunk 6]
```diff
@@ -27,7 +27,7 @@ Other types will currently be passed to default slot via `v-slot="{ data }"` or
 
 The `default`{lang=ts} slot can be used to render the content via `v-slot="{ data }"` syntax.
 
-```html [pages/[...slug.vue]]
+```html [pages/[...slug.vue\\]]
```
Comment (nobkd) [inline docs/content/4.api/1.components/2.content-renderer.md:30]:
```suggestion
```html [pages/[...slug\\].vue]
```

File: docs/content/4.api/1.components/2.content-renderer.md [hunk 7]
```diff
@@ -44,7 +44,7 @@ const { data } = await useAsyncData('page-data', () => queryContent('/hello').fi
 
 The `empty`{lang=ts} slot can be used to display a default content when the document is empty:
 
-```html [pages/[...slug.vue]]
+```html [pages/[...slug.vue\\]]
```
Comment (nobkd) [inline docs/content/4.api/1.components/2.content-renderer.md:47]:
```suggestion
```html [pages/[...slug\\].vue]
```

File: docs/content/4.api/1.components/4.content-query.md [hunk 8]
```diff
@@ -39,7 +39,7 @@ The `<ContentQuery>`{lang=html} component fetches a document and gives access to
 
 The `default`{lang=ts} slot can be used to render the content via `v-slot="{ data }"`{lang=html} syntax.
 
-```html [pages/[...slug.vue]]
+```html [pages/[...slug.vue\\]]
```
Comment (nobkd) [inline docs/content/4.api/1.components/4.content-query.md:42]:
```suggestion
```html [pages/[...slug\\].vue]
```

File: docs/content/4.api/1.components/7.prose.md [hunk 9]
```diff
@@ -70,6 +70,12 @@ Component properties will be:
 
 Check out the [highlight options](/api/configuration#highlight) for more about the syntax highlighting.
 
+::alert{type="warning"}
+If you want to use `]` in the filename, you need to escape it with 2 backslashes: `\\]`. This is necessary since JS will automatically escape the backslash in a string so `\\]` will be resolved as `\]`.
+
+Internally, a regex is used to extract filename.
```
Comment (nobkd) [inline docs/content/4.api/1.components/7.prose.md]:
```suggestion
Internally, a regex is used to extract the filename.
```

File: docs/content/4.api/1.components/1.content-doc.md [hunk 10]
```diff
@@ -73,7 +73,7 @@ The `empty`{lang=ts} slot can be used to display a default content before render
 
 ### Default
 
-```html [pages/[...slug.vue]]
+```html [pages/[...slug.vue\\]]
```
Comment (nobkd) [inline docs/content/4.api/1.components/1.content-doc.md:76]:
```suggestion
```html [pages/[...slug\\].vue]
```

File: docs/content/4.api/1.components/7.prose.md [hunk 11]
```diff
@@ -70,6 +70,10 @@ Component properties will be:
 
 Check out the [highlight options](/api/configuration#highlight) for more about the syntax highlighting.
 
+::alert{type="warning"}
+If you want to use `]` in the filename, you need to escape it with 2 backslashes: `\\]`. This is necessary since JS will automatically escape the backslash in a string so `\]` will be resolved as `]` breaking our regex.
```
Comment (nobkd) [inline docs/content/4.api/1.components/7.prose.md:74]: Is the rendered Markdown for `\]` and `\\] ` properly rendered, so we see the backslash(es)?
I think in code blocks we don't have to escape, but I'm not sure...

**Review by nobkd — CHANGES_REQUESTED** [review]
Here some small fixes, as in #2164

Everything else looks great to me, thanks 👍

File: playground/basic/components/content/ProseCode.vue [hunk 12]
```diff
@@ -0,0 +1,38 @@
+<script lang="ts" setup>
+const props = defineProps<{
+    code: string,
+    language?: string,
+    filename?: string,
+    highlights: number[],
+    meta?: string
+  }>()
+
+console.log(props)
```
Comment (farnabaz) [inline playground/basic/components/content/ProseCode.vue:10]:
```suggestion
```

File: playground/basic/components/content/ProseCode.vue [hunk 13]
```diff
@@ -0,0 +1,36 @@
+<script lang="ts" setup>
+const props = defineProps<{
```
Comment (farnabaz) [inline playground/basic/components/content/ProseCode.vue:2]:
```suggestion
defineProps<{
```

**Review by farnabaz — APPROVED** [review]
Thanks guys.
You're awesome ❤️

**Comment by nobkd** [comment]
Just to have this in one place, I think this bug was previously introduced with #2067

https://github.com/nuxt/content/pull/2067/files#diff-fd60d817a96ebccaa6b1456127b1e4589b3e10487ddb84362ab6e41ab1ede143L22-R23

I think, there was decided, that we could allow `[]` and `{}` in the meta part, and therefore changed the regex...
