### PR TITLE
fix: manage concurent initializations

### LINKED ISSUE #3129: Cloudflare Server Side Rendering fails on big pages.
### Environment

- Operating System: `Darwin`
- Node Version:     `v22.10.0`
- Nuxt Version:     `3.15.4`
- CLI Version:      `3.21.1`
- Nitro Version:    `2.10.4`
- Package Manager:  `npm@10.9.0`
- Builder:          `-`
- User Config:      `modules`, `target`, `image`, `sitemap`, `app`, `css`, `content`, `devServer`, `features`, `vue`, `vite`, `gtm`, `runtimeConfig`, `nitro`, `routeRules`, `build`, `optimization`, `multiCache`, `aos`, `devtools`, `compatibilityDate`
- Runtime Modules:  `@nuxt/devtools@2.0.0`, `@nuxt/image@1.9.0`, `nuxt-multi-cache@3.4.0`, `vue3-carousel-nuxt@1.1.5`, `nuxt-lazy-hydrate@1.0.0`, `nuxt-aos@1.2.5`, `@zadigetvoltaire/nuxt-gtm@0.0.13`, `@nuxtjs/sitemap@7.2.4`, `@nuxtjs/robots@5.2.2`, `@nuxt/content@3.1.1`
- Build Modules:    `-`

### Version

v3

### Reproduction

https://kestra.io/docs/expressions

### Description

When I navigate directly to https://kestra.io/docs/expressions I get a 500 error. 
But when I navigate to it through the UI, it works.
The website is hosted on cloudflare and we use a D1 database.

Because of it, I think the Server Side Rendering fails.

Looking at the D1 records, I see some malformed json for the body of `/docs/expressions`. The content is actually duplicated.

By chance, I found that D1 has a limit of 100 KB per request.

Could this be a clue?

### Additional context

_No response_

### Logs

```shell-script
{
  "truncated": false,
  "executionModel": "stateless",
  "outcome": "ok",
  "scriptVersion": {
    "id": "50513b55-c642-4e4c-b6e5-c0ee9e75b248"
  },
  "scriptName": "pages-worker--2240899-production",
  "diagnosticsChannelEvents": [],
  "exceptions": [],
  "logs": [
    {
      "message": [
        "[nuxt] [request error] [unhandled] [500]",
        "Unexpected non-whitespace character after JSON at position 120501 (line 1 column 120502)\n"
      ],
      "level": "error",
      "timestamp": 1739488360550
    },
    {
      "message": [
        "[url: POST /api/content/docs/query?v=m9wHgK551g] [status: 500] [length: -] [ip: -] [duration: 242ms]"
      ],
      "level": "error",
      "timestamp": 1739488360550
    },
    {
      "message": [
        "[url: GET /__nuxt_error?url=%2Fdocs%2Fconfiguration&statusCode=500&statusMessage&message=%5BPOST%5D+%22%2Fapi%2Fcontent%2Fdocs%2Fquery?v=m9wHgK551g%22:+500+&stack&data=%7B%22url%22:%22%2Fapi%2Fcontent%2Fdocs%2Fquery?v=m9wHgK551g%22,%22statusCode%22:500,%22statusMessage%22:%22%22,%22message%22:%22internal+server+error%22,%22stack%22:%22%22%7D] [status: 200] [length: -] [ip: 176.147.140.8] [duration: 48ms]"
      ],
      "level": "log",
      "timestamp": 1739488360599
    },
    {
      "message": [
        "[url: GET /docs/configuration] [status: 500] [length: -] [ip: 176.147.140.8] [duration: 295ms]"
      ],
      "level": "error",
      "timestamp": 1739488360600
    }
  ],
  "eventTimestamp": 1739488360304,
  "event": {
    "request": {
      "url": "https://kestra.io/docs/configuration",
      "method": "GET",
      "headers": {
        "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
        "accept-encoding": "gzip, br",
        "accept-language": "en-US,en;q=0.9",
        "cache-control": "max-age=0",
        "cf-connecting-ip": "176.147.140.8",
        "cf-connecting-o2o": "1",
        "cf-ipcountry": "FR",
        "cf-ray": "9118812bdceb1896",
        "cf-visitor": "{\"scheme\":\"https\"}",
        "connection": "Keep-Alive",
        "cookie": "REDACTED",
        "host": "kestra.io",
        "priority": "u=0, i",
        "sec-ch-ua": "\"Not(A:Brand\";v=\"99\", \"Google Chrome\";v=\"133\", \"Chromium\";v=\"133\"",
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"macOS\"",
        "sec-fetch-dest": "document",
        "sec-fetch-mode": "navigate",
        "sec-fetch-site": "same-origin",
        "sec-fetch-user": "?1",
        "upgrade-insecure-requests": "1",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36",
        "x-forwarded-for": "176.147.140.8",
        "x-forwarded-proto": "https",
        "x-real-ip": "176.147.140.8"
      },
      "cf": {
        "requestHeaderNames": {},
        "httpProtocol": "HTTP/3",
        "tlsCipher": "AEAD-AES128-GCM-SHA256",
        "continent": "EU",
        "asn": 5410,
        "clientAcceptEncoding": "gzip, br",
        "country": "FR",
        "isEUCountry": "1",
        "verifiedBotCategory": "",
        "requestPriority": "",
        "tlsClientAuth": {
          "certIssuerDNLegacy": "",
          "certIssuerSKI": "",
          "certSubjectDNRFC2253": "",
          "certSubjectDNLegacy": "",
          "certFingerprintSHA256": "",
          "certNotBefore": "",
          "certSKI": "",
          "certSerial": "",
          "certIssuerDN": "",
          "certVerified": "NONE",
          "certNotAfter": "",
          "certSubjectDN": "",
          "certPresented": "0",
          "certRevoked": "0",
          "certIssuerSerial": "",
          "certIssuerDNRFC2253": "",
          "certFingerprintSHA1": ""
        },
        "tlsClientExtensionsSha1": "",
        "tlsVersion": "TLSv1.3",
        "colo": "MRS",
        "timezone": "Europe/Paris",
        "region": "Auvergne-Rhône-Alpes",
        "longitude": "5.72040",
        "edgeRequestKeepAliveStatus": 1,
        "tlsClientRandom": "",
        "latitude": "45.17690",
        "postalCode": "38000",
        "city": "Grenoble",
        "regionCode": "ARA",
        "asOrganization": "Bouygues Telecom",
        "tlsClientHelloLength": "",
        "pagesHostName": "kestra-io.pages.dev",
        "botManagement": {
          "corporateProxy": false,
          "verifiedBot": false,
          "jsDetection": {
            "passed": false
          },
          "staticResource": false,
          "detectionIds": {},
          "score": 99
        }
      }
    },
    "response": {
      "status": 500
    }
  },
  "id": 13
}
```

### PR DESCRIPTION
**Pull request by elevatebart**
### 🔗 Linked issue

closes #3129

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Improve the concurent initialization of collections by waiting until one is finished to start another init.

#### Prevent double init

- At startup add a record in the info table to state we are about to init
- When launching a new loadAdapter(), check if info table and the init record are already here. If not, proceed with init.
- If already in the process of initialization, poll the table every 100ms to see if the record remains
- When the record has disappeared, return the query
- If a previous init of a previous version does not go all the way, the version will be different. Then we ignore the flag and init anyway.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: src/module.ts [hunk 1]
```diff
@@ -300,16 +296,29 @@ async function processCollectionItems(nuxt: Nuxt, collections: ResolvedCollectio
...
-      collectionChecksum[collection.name] = hash(collectionDump[collection.name])
+      collectionChecksum[collection.name] = hash(insertList)
 
+      // we start by telling everyone that we are setting up the collection
+      // so we create a new entry in the info table saying that it is not ready yet
       collectionDump[collection.name]!.push(
         generateCollectionTableDefinition(infoCollection, { drop: false }),
-        `DELETE FROM ${infoCollection.tableName} WHERE id = 'checksum_${collection.name}';`,
-        ...generateCollectionInsert(infoCollection, { id: `checksum_${collection.name}`, version: collectionChecksum[collection.name] }),
+        ...generateCollectionInsert(infoCollection, { id: `checksum_${collection.name}`, version: insertList, ready: false }),
```
Comment (farnabaz) [inline src/module.ts:310]:
```suggestion
        ...generateCollectionInsert(infoCollection, { id: `checksum_${collection.name}`, version: collectionChecksum[collection.name], ready: false }),
```

**Comment by elevatebart** [comment]
This is tested and works fine on https://kestra.io/docs

File: src/module.ts [hunk 2]
```diff
@@ -302,14 +298,27 @@ async function processCollectionItems(nuxt: Nuxt, collections: ResolvedCollectio
       }
       // Sort by file name to ensure consistent order
       list.sort((a, b) => String(a[0]).localeCompare(String(b[0])))
-      collectionDump[collection.name]!.push(...list.flatMap(([, sql]) => sql!))
+      const insertList = list.flatMap(([, sql]) => sql!)
 
-      collectionChecksum[collection.name] = hash(collectionDump[collection.name])
+      collectionChecksum[collection.name] = hash(insertList)
```
Comment (farnabaz) [inline src/module.ts:303]: With this change, the table definition is not used for hash generation. For example, if I change the default value of a number column in the table, we will still use the old table because the hash will not change.

File: src/runtime/internal/database.server.ts [hunk 3]
```diff
@@ -61,12 +61,30 @@ export async function checkAndImportDatabaseIntegrity(event: H3Event, collection
...
+      const interval = setInterval(async () => {
+        const { ready } = await db.first<{ ready: boolean }>(`select ready from ${tables.info} where id = ?`, [`checksum_${collection}`]).catch(() => ({ ready: true }))
+        if (ready) {
+          clearInterval(interval)
+          resolve(0)
+        }
+      }, 200)
+    })
+    return true
+  }
```
Comment (farnabaz) [inline src/runtime/internal/database.server.ts:80]: I think it is worth adding a timeout mechanism to this interval to make sure it always resolves.
Think of an edge case in which importing data fails when updating `ready` to `true`

File: src/runtime/internal/database.server.ts [hunk 4]
```diff
@@ -61,12 +61,30 @@ export async function checkAndImportDatabaseIntegrity(event: H3Event, collection
 async function _checkAndImportDatabaseIntegrity(event: H3Event, collection: string, integrityVersion: string, config: RuntimeConfig['content']) {
   const db = loadDatabaseAdapter(config)
 
-  const before = await db.first<{ version: string }>(`select * from ${tables.info} where id = ?`, [`checksum_${collection}`]).catch(() => ({ version: '' }))
+  const before = await db.first<{ version: string, ready: boolean }>(`select * from ${tables.info} where id = ?`, [`checksum_${collection}`]).catch(() => ({ version: '', ready: true }))
```
Comment (farnabaz) [inline src/runtime/internal/database.server.ts:64]: At first glance it is hard to understand why `read` is `true` in catch.
it would be better if we return `null` or `undefined` in catch and move the interval logic inside `if (before?.version) {`.

```ts

const before = await db.first<{ version: string, ready: boolean }>(`select * from ${tables.info} where id = ?`, [`checksum_${collection}`]).catch(() => null)

if (before?.version) {
  if (before.ready === true && before.version === integrityVersion) {
    return true
  }
  
  if (before.ready === false && before.version === integrityVersion) {
    // Loop 
  }
  
  // Delete old version -- checksum exists but does not match with bundled checksum
  await db.exec(`DELETE FROM ${tables.info} WHERE id = ?`, [`checksum_${collection}`])
}
```

**Review by farnabaz — CHANGES_REQUESTED** [review]
Thanks @elevatebart for the PR.
Using `ready` column as lock is smart 👍
I have two concerns regarding endless loop and invalid checksum (comments added)

And a suggestion to remove confusion from code

File: src/runtime/internal/database.server.ts (hunk 3 above)
Comment (elevatebart) [reply src/runtime/internal/database.server.ts]: totally agree. I added a 5 min timeout if it does not respond. Then I throw.

**Review by farnabaz — APPROVED** [review]
Thanks

**Comment by elevatebart** [comment]
I was in the process of testing it out, I hope I did not make any mistake...

**Comment by elevatebart** [comment]
And... famous last words, he made a few mistake and broke nuxt content
