### PR TITLE
fix: support components/content in layers for extends

### LINKED ISSUE #1386: Support `components/content` in `extends`

### PR DESCRIPTION
**Pull request by Atinux**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Resolves #1386 

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: src/module.ts [hunk 1]
```diff
@@ -346,27 +346,30 @@ export default defineNuxtModule<ModuleOptions>({
...
+    for (const layer of nuxt.options._layers) {
+      const srcDir = layer.config.srcDir
+      const globalComponents = resolve(srcDir, 'components/content')
+      const dirStat = await fs.promises.stat(globalComponents).catch(() => null)
+      if (dirStat && dirStat.isDirectory()) {
+        if (nuxt.options._layers.length === 1) {
+          logger.success('Using `~/components/content` for components in Markdown')
+        }
+        nuxt.hook('components:dirs', (dirs) => {
+          dirs.unshift({
```
Comment (pi0) [inline src/module.ts:358]: Unshift combined with multi-layer, causes layers overriding user dir

Comment (pi0) [reply src/module.ts:358]: ~> #1417
