### PR TITLE
fix(markdown): images src with `baseURL`

### LINKED ISSUE #1829: BaseURL is not added to images
### Environment

```sh
√ Using ArmoniK Docs Theme v0.1.0
RootDir: C:/Users/esoubiran/dev/armonik-docs-theme 
Nuxt project info:
------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.25.0`
- Builder:          `vite`
- User Config:      `app`, `extends`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

### Reproduction

- Create a Docus Project: 
- npx nuxi@latest init app -t themes/docus
- Add a `baseURL` in `nuxt.config.ts`
- Add an image using Markdown syntax
- Preview app

### Describe the bug

I expected images links to have been prefixed by the `baseURL` given in the `nuxt.config.ts`.

Here an example : https://aneoconsulting.github.io/armonik-docs-theme/guide/writing#images

Clicked on the preview link.

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by farnabaz**
### 🔗 Linked issue
resolves #1829
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: src/runtime/components/ContentRendererMarkdown.vue [hunk 1]
```diff
@@ -116,7 +117,17 @@ function renderNode (node: MarkdownNode, h: CreateElement, documentMeta: ParsedC
...
+    return renderToString(node)
+  }
+
+  // Resolve component props
+  const props = propsToData(node, documentMeta)
+
+  // Prepend base URL to absolute images
+  if (node.tag === 'img') {
+    if (props.src?.startsWith('/') && !props.src.startsWith('//')) {
+      props.src = withBase(props.src, useRuntimeConfig().app.baseURL)
```
Comment (Barbapapazes) [inline src/runtime/components/ContentRendererMarkdown.vue:129]: Nuxt API says that a env variable can be set to change the base URL

https://nuxt.com/docs/api/configuration/nuxt-config/#baseurl
