### PR TITLE
fix(module): make `documentDriven` configs optional

### LINKED ISSUE #1533: documentDriven object in nuxt.config has type error
### Environment

```
- Operating System: `Darwin`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.10`
- Nitro Version:    `0.5.3`
- Package Manager:  `pnpm@7.11.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
```

### Reproduction

https://stackblitz.com/edit/nuxt-starter-eabcly?file=nuxt.config.ts

### Describe the bug

Have you encountered such an error message?

image

Did I do something wrong there?

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by farnabaz**
### 🔗 Linked issue
resolves  #1533

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: src/module.ts [hunk 1]
```diff
@@ -174,14 +174,14 @@ export interface ModuleOptions {
    * Document-driven mode config
```
Comment (Atinux) [inline src/module.ts:174]: Should we add default as well?
